S_max: 2.0
S_thr: 0.3
a_max: 0.2
c_max: 0.058
d_safe: 0.8
dt: 0.2
episode_len: 2500
feed_radius: 2.8
height: 35.0
k_neighbors: 7
n_agents: 12
n_patches: 10
regen_r: 0.24
turn_max: 0.3
v_max: 1.5
width: 35.0
