S_max: 1.5
S_thr: 0.3
a_max: 0.25
c_max: 0.05
d_safe: 0.8
dt: 0.2
episode_len: 3000
feed_radius: 2.5
height: 60.0
k_neighbors: 8
n_agents: 15
n_patches: 8
regen_r: 0.15
turn_max: 0.35
v_max: 1.8
width: 60.0
