S_max: 2.5
S_thr: 0.3
a_max: 0.18
c_max: 0.07
d_safe: 0.8
dt: 0.2
episode_len: 2500
feed_radius: 3.5
height: 28.0
k_neighbors: 6
n_agents: 10
n_patches: 15
regen_r: 0.32
turn_max: 0.28
v_max: 1.35
width: 28.0
