S_max: 3.0
S_thr: 0.6
a_max: 0.2
c_max: 0.08
d_safe: 0.6
dt: 0.2
episode_len: 2000
feed_radius: 4.0
height: 20.0
k_neighbors: 4
n_agents: 5
n_patches: 20
regen_r: 0.4
turn_max: 0.3
v_max: 1.5
width: 20.0
